version: 0.2
env:
  secrets-manager:
    LOGIN: prod/sonar:sonartoken
    HOST: prod/sonar:HOST
    Organization: prod/sonar:Organization
    Project: prod/sonar:Project
phases:
  build:
    commands:
      - echo "Hello Kasper, We are in Pre-build"
  post_build:
    commands:
    - echo "Deployed to S3"
artifacts:
  files:
    - '**/*'
